# Generated by Django 2.2.5 on 2019-11-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0002_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='id_number',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
