# Generated by Django 2.2.5 on 2019-11-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0003_measurement_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
