# Generated by Django 2.2.5 on 2019-11-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0004_measurement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
