# Generated by Django 2.2.5 on 2019-11-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0005_remove_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='height',
        ),
    ]
