# Generated by Django 2.2.5 on 2019-11-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0006_auto_20191120_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='birthday',
        ),
    ]
