# Generated by Django 2.2.5 on 2019-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0008_auto_20191120_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100)),
                ('risk', models.CharField(max_length=100)),
                ('risk_proba', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
    ]
