# Generated by Django 2.2.5 on 2019-12-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0009_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='diastolic',
            new_name='birthdate',
        ),
        migrations.AddField(
            model_name='measurement',
            name='height',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
