# Generated by Django 2.2.5 on 2019-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0010_auto_20191201_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='age',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='glucose',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='smoke',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
