# Generated by Django 2.2.5 on 2019-12-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0011_auto_20191202_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='dia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='nurse',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='pulse',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
