# Generated by Django 2.2.5 on 2019-12-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0012_auto_20191226_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='diabetes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
