# Generated by Django 2.2.5 on 2019-12-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0013_measurement_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sex',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
