# Generated by Django 2.2.5 on 2019-12-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0014_measurement_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
