# Generated by Django 2.2.5 on 2019-12-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0015_measurement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
