# Generated by Django 2.2.5 on 2019-12-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0017_auto_20191226_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='diastolic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
