# Generated by Django 2.2.5 on 2020-01-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0019_patient_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assess',
        ),
    ]
