# Generated by Django 2.2.5 on 2020-01-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0021_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.CharField(max_length=100)),
            ],
        ),
    ]
