# Generated by Django 2.2.5 on 2020-01-23 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRU', '0022_logmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurepatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
