# Generated by Django 2.2.5 on 2020-01-26 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0023_measurement_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='risk',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='risk_proba',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
