# Generated by Django 2.2.5 on 2020-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0024_auto_20200126_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='created_at',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='name',
            new_name='month',
        ),
        migrations.AddField(
            model_name='measurement',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='risk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='risk_proba',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
