# Generated by Django 2.2.5 on 2020-02-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0026_measurement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='BMI',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
