# Generated by Django 2.2.5 on 2019-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
