# Generated by Django 2.2.5 on 2019-12-30 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test2', '0003_rprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rProfile',
            new_name='Profile',
        ),
    ]
