# Generated by Django 2.2.5 on 2019-12-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0009_medicuserprofile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicuserprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='medicuserprofile',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicuserprofile',
            name='birthdate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicuserprofile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicuserprofile',
            name='sex',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicuserprofile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getmedics', to=settings.AUTH_USER_MODEL),
        ),
    ]
