# Generated by Django 2.2.5 on 2020-01-10 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0012_patientuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuserprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='height',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='is_dia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
