# Generated by Django 2.2.5 on 2020-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0013_auto_20200110_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicuserprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
