# Generated by Django 2.2.5 on 2020-01-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0016_patientuserprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuserprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
