# Generated by Django 2.2.5 on 2020-02-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0017_auto_20200129_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicuserprofile',
            name='bday',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicuserprofile',
            name='bmonth',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicuserprofile',
            name='byear',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='bday',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='bmonth',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='byear',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
