# Generated by Django 2.2.5 on 2020-02-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0018_auto_20200224_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicuserprofile',
            old_name='bday',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patientuserprofile',
            old_name='bday',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='medicuserprofile',
            name='bmonth',
        ),
        migrations.RemoveField(
            model_name='medicuserprofile',
            name='byear',
        ),
        migrations.RemoveField(
            model_name='medicuserprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientuserprofile',
            name='bmonth',
        ),
        migrations.RemoveField(
            model_name='patientuserprofile',
            name='byear',
        ),
    ]
