# Generated by Django 2.2.5 on 2020-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0019_auto_20200224_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuserprofile',
            name='smoker',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
