# Generated by Django 2.2.5 on 2020-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0020_patientuserprofile_smoker'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicuserprofile',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
